name: Lint,Test,Deploy

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  lint_test_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Node setup
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - name: install dependencies
        run: npm ci

      - name: lint
        run: npm run lint:affected

      - name: test
        run:  npm run test:affected

      - name: deploy
        if: ${{ github.event.name == 'push'}}
        run:  npm run deploy:affected